
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Phalcon S| Login</title>
    <link href="/css/bootstrap.css" rel="stylesheet">

    <style>
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #fff;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: normal;
        }
        .form-signin .form-control {
            position: relative;
            font-size: 16px;
            height: auto;
            padding: 10px;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

</head>

<body>

<div class="container">

    <?=  $this->flashSession->output() ?>

    <form class="form-signin" method="post">
        <h2 class="form-signin-heading">Admin module login</h2>
        <input name="username" type="text" class="form-control" placeholder="Username" autofocus> <br>
        <input name="password" type="password" class="form-control" placeholder="Password">
        <label class="checkbox">
            <input name="remember-me" type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-block" type="submit">Sign in</button>
    </form>

</div>



</body>
</html>