<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/templates/header.phtml';
?>


        <div class="jumbotron">
            <h1>Front module started by default</h1>
        </div>

        <div class="row marketing">
            <div class="col-lg-6">
                <h4>Lorem ipsum dolor sit amet</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Proin quis fringilla justo, sed suscipit erat. Morbi dictum risus cursus,
                    eleifend lacus eu, sagittis lectus. Integer sed tellus vitae quam dapibus dignissim.
                    Phasellus bibendum nisi vel tempor eleifend. Maecenas venenatis tellus sem, et fringilla tortor consectetur in.
                    Maecenas scelerisque libero sit amet purus mollis, eu porta neque vulputate. Maecenas at accumsan tortor.</p>
            </div>

            <div class="col-lg-6">
                <h4>Lorem ipsum dolor sit amet</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    Proin quis fringilla justo, sed suscipit erat. Morbi dictum risus cursus,
                    eleifend lacus eu, sagittis lectus. Integer sed tellus vitae quam dapibus dignissim.
                    Phasellus bibendum nisi vel tempor eleifend. Maecenas venenatis tellus sem, et fringilla tortor consectetur in.
                    Maecenas scelerisque libero sit amet purus mollis, eu porta neque vulputate. Maecenas at accumsan tortor.</p></div>
        </div>



<?php
require_once $_SERVER['DOCUMENT_ROOT'] . '/templates/footer.phtml';
?>